In [24]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
df2=pd.read_csv(r"C:\Users\bhagy\OneDrive\Desktop\practice\Emp_Data.csv")

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   EmpID    29 non-null     int64
 1   FName    29 non-null     object
 2   LName    29 non-null     object
 3   Gender   29 non-null     object
 4   Age      29 non-null     int64
 5   EMail    29 non-null     object
 6   Salary   29 non-null     int64
 7   LOC      29 non-null     object
 8   MGR_ID   29 non-null     int64
 9   DEPT_ID  29 non-null     int64
dtypes: int64(5), object(5)
memory usage: 2.4+ KB

In [27]:
df2.head()

,EmpID,FName,LName,Gender,Age,EMail,Salary,LOC,MGR_ID,DEPT_ID
0,677509,Lois,Walker,F,22,lois.walker@hotmail.com,168251,DALLAS,677509,10
1,940761,Brenda,Robinson,F,43,brenda.robinson@gmail.com,51063,CHICAGO,940761,10
2,428945,Joe,Robinson,M,32,joe.robinson@gmail.com,50155,CHICAGO,372661,10
3,408351,Diane,Jon,F,25,diane.evans@yahoo.com,180294,NEW YORK,217421,20
4,193819,Benjamin,Russell,M,45,benjamin.russell@charter.net,117642,DALLAS,408951,20

In [28]:
from sklearn.preprocessing import LabelEncoder
df2['Gender']=LabelEncoder().fit_transform(df2['Gender'])

df2.head()

,EmpID,FName,LName,Gender,Age,EMail,Salary,LOC,MGR_ID,DEPT_ID
0,677509,Lois,Walker,0,22,lois.walker@hotmail.com,168251,DALLAS,677509,10
1,940761,Brenda,Robinson,0,43,brenda.robinson@gmail.com,51063,CHICAGO,940761,10
2,428945,Joe,Robinson,1,32,joe.robinson@gmail.com,50155,CHICAGO,372661,10
3,408351,Diane,Jon,0,25,diane.evans@yahoo.com,180294,NEW YORK,217421,20
4,193819,Benjamin,Russell,1,45,benjamin.russell@charter.net,117642,DALLAS,408951,20

In [29]:
from sklearn.preprocessing import LabelEncoder
df2['Gender']=LabelEncoder().fit_transform(df2['Gender'])
df2['LOC']=LabelEncoder().fit_transform(df2['LOC'])
df2.head()

,EmpID,FName,LName,Gender,Age,EMail,Salary,LOC,MGR_ID,DEPT_ID
0,677509,Lois,Walker,0,22,lois.walker@hotmail.com,168251,1,677509,10
1,940761,Brenda,Robinson,0,43,brenda.robinson@gmail.com,51063,0,940761,10
2,428945,Joe,Robinson,1,32,joe.robinson@gmail.com,50155,0,372661,10
3,408351,Diane,Jon,0,25,diane.evans@yahoo.com,180294,4,217421,20
4,193819,Benjamin,Russell,1,45,benjamin.russell@charter.net,117642,1,408951,20

In [32]:
df2[['LOC']].value_counts()

LOC
0      9
1      8
4      4
5      4
2      2
3      2
Name: count, dtype: int64

In [36]:
import pandas as pd
df2=pd.read_csv(r"C:\Users\bhagy\OneDrive\Desktop\practice\Emp_Data.csv")
df2.shape
dummy1=pd.get_dummies(df2,columns=['LOC'])
dummy1

,EmpID,FName,LName,Gender,Age,EMail,Salary,MGR_ID,DEPT_ID,LOC_CHICAGO,LOC_DALLAS,LOC_Delhi,LOC_Mumbai,LOC_NEW YORK,LOC_Pune
0,677509,Lois,Walker,F,22,lois.walker@hotmail.com,168251,677509,10,False,True,False,False,False,False
1,940761,Brenda,Robinson,F,43,brenda.robinson@gmail.com,51063,940761,10,True,False,False,False,False,False
2,428945,Joe,Robinson,M,32,joe.robinson@gmail.com,50155,372661,10,True,False,False,False,False,False
3,408351,Diane,Jon,F,25,diane.evans@yahoo.com,180294,217421,20,False,False,False,False,True,False
4,193819,Benjamin,Russell,M,45,benjamin.russell@charter.net,117642,408951,20,False,True,False,False,False,False
5,499687,Patrick,Bailey,M,43,patrick.bailey@aol.com,72305,499687,20,True,False,False,False,False,False
6,539712,Nancy,Baker,F,23,nancy.baker@bp.com,98189,539712,30,False,True,False,False,False,False
7,380086,Carol,Murphy,F,31,carol.murphy@gmail.com,60918,380086,30,False,False,False,False,True,False
8,477616,Frances,Young,F,21,frances.young@gmail.com,121587,477616,30,False,False,False,False,False,True
9,162402,Diana,Peterson,F,24,diana.peterson@hotmail.co.uk,43010,403709,30,False,False,False,False,True,False
10,231469,Ralph,Flores,M,35,ralph.flores@yahoo.com,118457,372661,30,False,False,False,True,False,False
11,153989,Jack,Alexander,M,54,jack.alexander@gmail.com,82965,341613,10,False,True,False,False,False,False
12,386158,Melissa,King,F,19,melissa.king@comcast.net,166892,310565,20,True,False,False,False,False,False
13,301576,Wayne,Watson,M,23,wayne.watson@gmail.com,92758,279517,20,False,False,False,False,False,True
14,441771,Cheryl,Scott,F,43,cheryl.scott@gmail.com,92220,248469,20,False,True,False,False,False,False
15,528509,Paula,Diaz,F,55,paula.diaz@gmail.com,152654,217421,20,True,False,False,False,False,False
16,912990,Joshua,Stewart,M,45,joshua.stewart@yahoo.ca,184896,186373,10,False,False,True,False,False,False
17,214352,Theresa,Lee,F,34,theresa.lee@gmail.com,197537,155325,30,False,False,False,False,True,False
18,890290,Julia,Scott,F,37,julia.scott@apple.com,141518,124277,10,False,True,False,False,False,False
19,622406,Thomas,Lewis,M,21,thomas.lewis@gmail.com,73862,93229,20,True,False,False,False,False,False
20,979607,Carol,Edwards,F,22,carol.edwards@msn.com,93967,62181,20,False,True,False,False,False,False
21,969580,Matthew,Turner,M,20,matthew.turner@gmail.com,52237,31133,20,False,True,False,False,False,False
22,241469,Ralph,Rocky,M,35,ralph.flores@yahoo.com,118457,372661,30,False,False,False,False,False,True
23,1539989,Jack,Alexander2,M,54,jack.alexander@gmail.com,82965,341613,10,False,False,False,True,False,False
24,389158,Melissa,Kings,F,19,melissa.king@comcast.net,166892,310565,20,True,False,False,False,False,False
25,301516,Wayne,Watsonewr,M,23,wayne.watson@gmail.com,92758,279517,20,True,False,False,False,False,False
26,441761,Cheryl,Scottyy,F,43,cheryl.scott@gmail.com,92220,248469,20,False,False,False,False,False,True
27,528539,Paula,Diaz12,F,55,paula.diaz@gmail.com,152654,217421,20,True,False,False,False,False,False
28,912890,Joshua,Stewartwewr,M,45,joshua.stewart@yahoo.ca,184896,186373,10,False,False,True,False,False,False